name: SonarCloud Analysis
on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install SonarScanner
        run: |
          sudo apt-get install -y openjdk-17-jdk
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
          unzip sonar-scanner-cli-4.8.0.2856-linux.zip
          echo "$GITHUB_WORKSPACE/sonar-scanner-4.8.0.2856/bin" >> $GITHUB_PATH
      
      - name: Run SonarScanner
        run: |
          sonar-scanner \
            -Dsonar.projectKey=lisopilkKa_test \
            -Dsonar.organization=lisopilkka \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}